package main

import _ "embed"

// payload.zip is generated by scripts/build_next_installer.ps1.
// The uninstaller is compiled against a tiny empty ZIP; the installer is then
// rebuilt with the real application payload including Uninstall.exe.
//
//go:embed payload.zip
var payload []byte
