$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$goFiles = Get-ChildItem installer_next,patcher,silent_updater -Recurse -Filter *.go | ForEach-Object { $_.FullName }
if (-not $goFiles) { throw 'Go release sources not found' }

$notFormatted = @(& gofmt -l $goFiles)
if ($LASTEXITCODE -ne 0) { throw 'gofmt failed' }
if ($notFormatted.Count -gt 0) {
    Write-Warning 'Some historical Go sources are not gofmt-clean. go vet remains mandatory.'
    $notFormatted | ForEach-Object { Write-Host "gofmt diagnostic: $_" }
}

# Embedded payload files are generated by the builders. Harmless temporary
# fixtures let go vet compile all three modules before an installer is produced.
python -c "import zipfile; zipfile.ZipFile(r'installer_next/payload.zip','w').close(); zipfile.ZipFile(r'patcher/patch_payload.zip','w').close()"
if ($LASTEXITCODE -ne 0) { throw 'Could not create Go vet payload fixtures' }
Set-Content -LiteralPath 'patcher/patch_manifest.json' -Value '{}' -Encoding utf8NoBOM

try {
    Push-Location installer_next
    try {
        # WM_DRAWITEM lParam is the single intentional Windows ABI pointer
        # conversion and has a dedicated regression test.
        go vet -unsafeptr=false ./...
        if ($LASTEXITCODE -ne 0) { throw 'installer_next go vet failed' }
    } finally { Pop-Location }

    Push-Location patcher
    try {
        go vet ./...
        if ($LASTEXITCODE -ne 0) { throw 'patcher go vet failed' }
    } finally { Pop-Location }

    Push-Location silent_updater
    try {
        go vet ./...
        if ($LASTEXITCODE -ne 0) { throw 'silent_updater go vet failed' }
    } finally { Pop-Location }
} finally {
    Remove-Item -Force -ErrorAction SilentlyContinue 'installer_next/payload.zip'
    Remove-Item -Force -ErrorAction SilentlyContinue 'patcher/patch_payload.zip'
    Remove-Item -Force -ErrorAction SilentlyContinue 'patcher/patch_manifest.json'
}

Write-Host 'GO RELEASE AUDIT OK'
