from __future__ import annotations

import ast
import py_compile
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "linkvideo_vpn_helper"


def fail(message: str) -> None:
    raise SystemExit("SELF-CHECK FAILED: " + message)


# 1. Every Python file must compile.
for path in sorted(SRC.rglob("*.py")):
    try:
        py_compile.compile(str(path), doraise=True)
    except Exception as exc:
        fail(f"{path.relative_to(ROOT)}: {exc}")

# 1b. UI classes must not call private self-methods that do not exist.
# Python compiles such code successfully and only fails when the affected page is opened.
for path in sorted((SRC / "ui").rglob("*.py")):
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for cls in (node for node in ast.walk(tree) if isinstance(node, ast.ClassDef)):
        methods = {
            node.name
            for node in cls.body
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        }
        assigned = set()
        calls = set()
        for node in ast.walk(cls):
            if isinstance(node, (ast.Assign, ast.AnnAssign)):
                targets = node.targets if isinstance(node, ast.Assign) else [node.target]
                for target in targets:
                    if (
                        isinstance(target, ast.Attribute)
                        and isinstance(target.value, ast.Name)
                        and target.value.id == "self"
                    ):
                        assigned.add(target.attr)
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id == "self"
                and node.func.attr.startswith("_")
            ):
                calls.add(node.func.attr)
        missing = sorted(calls - methods - assigned)
        if missing:
            fail(
                f"{path.relative_to(ROOT)}:{cls.name} calls missing private method(s): "
                + ", ".join(missing)
            )

# 2. One authoritative release version and current release notes.
version_text = (SRC / "version.py").read_text(encoding="utf-8")
m = re.search(r'^APP_VERSION\s*=\s*["\']([^"\']+)["\']', version_text, re.M)
if not m:
    fail("APP_VERSION not found")
version = m.group(1)

# Startup contract: app.py imports these names directly.
for required_name in ("APP_NAME", "APP_VERSION", "APP_PUBLISHER"):
    if not re.search(rf"^{required_name}\s*=", version_text, re.M):
        fail(f"version.py missing required startup constant: {required_name}")

# Import the version module so missing/invalid startup symbols are caught before release.
import importlib.util
_spec = importlib.util.spec_from_file_location("_lv_version_check", SRC / "version.py")
_mod = importlib.util.module_from_spec(_spec)
assert _spec and _spec.loader
_spec.loader.exec_module(_mod)
if _mod.APP_NAME != "LinkVideo.Helper":
    fail(f"unexpected APP_NAME: {_mod.APP_NAME!r}")
if not getattr(_mod, "APP_PUBLISHER", ""):
    fail("APP_PUBLISHER is empty")
notes = ROOT / f"RELEASE_{version}_RU.txt"
if not notes.exists() or not notes.read_text(encoding="utf-8").strip():
    fail(f"release notes missing or empty: {notes.name}")

# 3. Required product scope: no removed maintenance modules in the new package.
for forbidden in ("server_maintenance", "client_check_page"):
    matches = [p for p in SRC.rglob("*.py") if forbidden in p.name]
    if matches:
        fail(f"removed module still present: {matches[0].name}")

# 4. Built-in VPN list must contain exact 2.0 defaults.
registry_text = (SRC / "services" / "server_registry.py").read_text(encoding="utf-8")
for i in range(1, 11):
    # vpn01-vpn10 are generated by code, assert the generator contract instead of importing PySide6.
    pass
if 'range(1, 11)' not in registry_text:
    fail("vpn01-vpn10 default generator missing")
for host in ("rb-vpn01.linkvideo.ru", "kz-vpn01.linkvideo.ru"):
    if host not in registry_text:
        fail(f"built-in regional server missing: {host}")

# 5. Never ship a private key from the project tree.
for path in ROOT.rglob("*"):
    if not path.is_file():
        continue
    name = path.name.lower()
    if name in {"private_key", "id_rsa"} or name.endswith((".pem", ".key")):
        fail(f"private key-like file found: {path.relative_to(ROOT)}")
    if path.suffix.lower() in {".py", ".txt", ".md", ".json", ".iss", ".bat", ".yml", ".yaml"}:
        try:
            content = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if re.search(
            r"-----BEGIN PRIVATE KEY-----\s+[A-Za-z0-9+/=\r\n]{80,}-----END PRIVATE KEY-----",
            content,
            re.MULTILINE,
        ):
            fail(f"private key material found: {path.relative_to(ROOT)}")


# 6. Release UI contracts fixed during the 2.0 redesign.
search_ui = (SRC / "ui" / "pages" / "search_manage_page.py").read_text(encoding="utf-8")
if '[("login", "По логину"), ("port", "По порту")]' not in search_ui:
    fail("search modes must be login + port only")
if "WinBox" in search_ui or "winbox" in search_ui.lower():
    fail("WinBox action must not be present in 2.0 client UI")

create_ui = (SRC / "ui" / "pages" / "create_client_page.py").read_text(encoding="utf-8")
if 'x.country == "Россия"' not in create_ui:
    fail("automatic server choice must be restricted to Russia")
if "self.counters_row" not in create_ui:
    fail("ports/accounts controls must share one horizontal work row")

settings_ui = (SRC / "ui" / "pages" / "settings_page.py").read_text(encoding="utf-8")
if "setMaximumWidth(1080)" in settings_ui:
    fail("settings page must not be constrained to the old centered 1080px column")

theme_text = (SRC / "theme.py").read_text(encoding="utf-8")
if "QPushButton#DateTimeField {{ text-align: center" not in theme_text:
    fail("archive date/time fields must be centered")

if not (SRC / "services" / "archive_diagnosis_engine.py").exists():
    fail("archive diagnosis engine missing")


# 7. Final RC06 interaction contracts.
components_ui = (
    (SRC / "ui" / "components.py").read_text(encoding="utf-8")
    + "\n"
    + (SRC / "ui" / "components_compat.py").read_text(encoding="utf-8")
)
if "def eventFilter(self, watched, event):" not in components_ui or "_close_popup" not in components_ui:
    fail("date/time popup must close when clicking outside")

main_ui = (SRC / "ui" / "main_window.py").read_text(encoding="utf-8")
if "Qt.Key.Key_Escape" not in main_ui or "cancel_current_action" not in main_ui:
    fail("ESC global cancellation routing missing")

if 'self.task.done("Клиент найден"' in search_ui:
    fail("successful search must not show redundant Client found banner")
if 'item.setSizeHint(QSize(0, 42))' not in search_ui:
    fail("client port rows must use compact fixed row height")
if 'self.result_text = QTextEdit()' not in create_ui:
    fail("created client result must use classic 1.1.2 text block")

archive_ui = (SRC / "ui" / "pages" / "archive_download_page.py").read_text(encoding="utf-8")
diag_ui = (SRC / "ui" / "pages" / "archive_diagnostics_page.py").read_text(encoding="utf-8")
for name, text in (("archive", archive_ui), ("diagnostics", diag_ui)):
    if "def cancel_current_action" not in text:
        fail(f"ESC cancellation missing on {name} page")
if "params.insertWidget(0, self.auth_row_widget)" not in archive_ui:
    fail("B2O status must be above archive period")
if "B2O-статус всегда расположен над периодом" not in diag_ui:
    fail("B2O status must be above diagnostics period")


# 8. Final window/scroll/API contracts (RC07).
if "self.resize(1380, 900)" not in main_ui:
    fail("3.0 startup window must be 1380x900")
if 'self.version.setAlignment(Qt.AlignmentFlag.AlignCenter)' not in main_ui:
    fail("sidebar version must be centered below Settings")
for name, text in (("search", search_ui), ("archive", archive_ui), ("diagnostics", diag_ui)):
    if 'build_page_scaffold' not in text or 'self.page_canvas' not in text:
        fail(f"{name} page must use the centered responsive page scaffold")
if 'build_page_scaffold' not in create_ui or 'min_width=860' not in create_ui:
    fail("create page must use the 3.0 responsive workbench scaffold")
if 'rl.addWidget(self.copy_all, 0, Qt.AlignmentFlag.AlignLeft)' not in create_ui:
    fail("created-client copy button must be aligned left")
api_client_text = (SRC / "mikrotik" / "api_ssl_client.py").read_text(encoding="utf-8")
if "ports.append(8729)" not in api_client_text or "_port_cache" not in api_client_text:
    fail("RouterOS API 8728->8729 fallback/caching missing")
if "WinBox доступен, но RouterOS API 8728/8729" not in api_client_text:
    fail("RouterOS API failure must explain the WinBox-vs-API distinction")


# 9. Final country/operator + regional search contracts (RC08).
archive_service_text = (
    (SRC / "services" / "archive_service.py").read_text(encoding="utf-8")
    + "\n"
    + (SRC / "services" / "archive_service_core.py").read_text(encoding="utf-8")
)
for token in ('"country": "Россия"', '"camera_prefix": "linkvideo_"', '"country": "Казахстан"', '"camera_prefix": "linkvideokz_"', '"country": "Беларусь"', '"camera_prefix": "linkvideoby_"'):
    if token not in archive_service_text:
        fail("fixed archive operator map missing: " + token)
for token in ('"cluster": "linkvideokz"', '"cluster": "linkvideoby"', 'kz-vcore01.video.goodline.info', 'rb-vcore01.video.goodline.info'):
    if token not in archive_service_text:
        fail("regional archive profile missing: " + token)

search_service_text = (
    (SRC / "services" / "search_service.py").read_text(encoding="utf-8")
    + "\n"
    + (SRC / "services" / "search_service_core.py").read_text(encoding="utf-8")
)
if 'low.startswith(q + "_")' not in search_service_text:
    fail("login search must include generated suffixes on regional servers")
if 'suggest_free_login_all(self.registry.hosts()' in create_ui:
    fail("client creation must not choose login suffix globally across all VPN servers")
if 'self.service.suggest_next_login(chosen, self.credentials, login)' not in create_ui:
    fail("client creation must choose login suffix only on the selected/chosen server")

for name, text in (("archive", archive_ui), ("diagnostics", diag_ui)):
    for country_choice in ('"241", "Россия"', '"1721", "Казахстан"', '"1741", "Беларусь"'):
        if country_choice not in text:
            fail(f"{name} page missing fixed country choice: {country_choice}")
    for visible_id in ("Россия · 241", "Казахстан · 1721", "Беларусь · 1741"):
        if visible_id in text:
            fail(f"{name} page must not expose internal B2O operator IDs")

if 'self.operator = QLineEdit' in settings_ui or 'def _save_operator' in settings_ui:
    fail("operator IDs must not be editable in Settings")

if 'QFrame#ResultCard[selected=\"true\"]' not in theme_text:
    fail("selected client/port highlight must remain visible")

# 10. Final archive-client / regional archive contracts (RC09).
inactive_ui_path = SRC / "ui" / "pages" / "inactive_clients_page.py"
if not inactive_ui_path.exists():
    fail("inactive client archive page missing")
inactive_ui = inactive_ui_path.read_text(encoding="utf-8")
if "INACTIVE_DAYS = 30" not in inactive_ui or "list_lifecycle_clients" not in inactive_ui:
    fail("VPN clients page must use lifecycle scan from 30 days")
if '("inactive", "⌛", "VPN-клиенты"' not in main_ui:
    fail("VPN clients navigation item missing")
if "Остальные найденные результаты остаются на месте" not in search_ui:
    fail("deleting one client must preserve remaining search results")
if 'self.settings_btn.setStyleSheet("QPushButton { text-align:center; padding-left:0px; }")' not in main_ui:
    fail("Settings button must be centered in sidebar")
if "def archive_servers(self, operator_id" not in archive_service_text or "archive/custom_servers/" not in archive_service_text:
    fail("regional archive server registry must be extensible")
if "camera_section = QLabel(\"Камера\")" not in diag_ui or "period_section = QLabel(\"Период проверки\")" not in diag_ui:
    fail("diagnostics form must have clear Camera and Period sections")
if 'operator_label = QLabel("Страна")' not in diag_ui:
    fail("diagnostics must show country instead of internal operator ID")

# 11. Media-server auto-discovery / clean country UI (RC10).
if "DVR_SERVERS_URL" not in archive_service_text or "/dvr-servers" not in archive_service_text:
    fail("B2O media-server endpoint missing")
if "def dvr_servers(" not in archive_service_text or "cached_dvr_servers" not in archive_service_text:
    fail("B2O media-server discovery/cache missing")
if "archive_servers(operator_id, online=True)" not in archive_service_text:
    fail("regional deep fallback must use live B2O media-server list")
if "Архивные серверы" in settings_ui or "Обновить из B2O" in settings_ui:
    fail("3.0.3 must keep internal archive-server inventory out of Settings UI")
if "SERVERS_URL" not in archive_service_text or "/servers" not in archive_service_text:
    fail("3.0.3 B2O server inventory endpoint candidate missing")
if "range(1, 501)" in archive_service_text:
    fail("3.0.3 must not brute-force b2o-vcore1..500")
if "_parse_hls_segments" not in archive_service_text or "player playlist" not in archive_service_text:
    fail("3.0.3 player-playlist DVR routing missing")
for visible_id in ("Россия · 241", "Казахстан · 1721", "Беларусь · 1741", "Оператор 241", "Оператор 1721", "Оператор 1741"):
    if visible_id in settings_ui + archive_ui + diag_ui:
        fail("internal operator ID must not be visible in UI: " + visible_id)

# 12. Inactive-client archive bulk management / sorting (RC12).
inactive_ui = inactive_ui_path.read_text(encoding="utf-8")
for token in (
    '"Старые"',
    '"Новые"',
    '"По серверу"',
    '"Выбрать все"',
    '"Очистить выбор"',
    'Ctrl + клик',
    '"Включить"',
    '"Отключить"',
    '"Удалить"',
):
    if token not in inactive_ui:
        fail("inactive client archive modern selection/sort control missing: " + token)
if '"По логину"' in inactive_ui:
    fail("inactive client archive must not expose login sorting")
if "_selected_keys" not in inactive_ui or "Qt.KeyboardModifier.ControlModifier" not in inactive_ui or "_run_batch" not in inactive_ui:
    fail("inactive client archive must support Ctrl+click multi-selection and batch actions")
if "sort_inactive_records" not in (SRC / "services" / "vpn_service.py").read_text(encoding="utf-8"):
    fail("inactive client archive sort helper missing")
if 'QFrame#ArchiveClientCard[bulk="true"]' not in theme_text:
    fail("multi-selected inactive client cards must have a modern visible selected state")
if "self.resize(1380, 900)" not in main_ui:
    fail("default LinkVideo.Helper 3.0 window size must be 1380x900")

# 13. VPN Automation 2.1.1 contracts.
auto_path = SRC / "services" / "vpn_automation_service.py"
lifecycle_path = SRC / "services" / "vpn_lifecycle.py"
servers_page_path = SRC / "ui" / "pages" / "vpn_servers_page.py"
if not auto_path.exists() or not lifecycle_path.exists():
    fail("VPN Automation service/lifecycle modules missing")
auto_text = (
    auto_path.read_text(encoding="utf-8")
    + "\n"
    + (SRC / "services" / "vpn_automation_service_core.py").read_text(encoding="utf-8")
)
life_text = lifecycle_path.read_text(encoding="utf-8")
servers_text = servers_page_path.read_text(encoding="utf-8")
for token in ("LV-Activity", "LV-Aging", "LV-AutoRestore", "login failure for user", "memory-lines", "set_quarantine_enabled", "seed_lifecycle"):
    if token not in auto_text:
        fail("VPN Automation contract missing: " + token)
for token in ("|LV1|", "state=A", "last="):
    if token not in life_text + auto_text:
        fail("VPN lifecycle marker contract missing: " + token)
for token in ("Установить/обновить LV на всех", "Выгрузить все серверы", "Инициализировать активность", "Остановить LV", "Запустить LV", "Остановить LV на всех", "Запустить LV на всех", "backup_one"):
    if token not in servers_text:
        fail("VPN servers automation UI missing: " + token)
if "set_automation_enabled" not in auto_text or "LV-Resume-Aging=" not in auto_text:
    fail("LV full start/stop control with quarantine resume state missing")
if 'state = "A" if enabled else "M"' not in (SRC / "services" / "vpn_service.py").read_text(encoding="utf-8"):
    fail("manual Helper disable must be marked as lifecycle M")

print(f"SELF-CHECK OK — LinkVideo.Helper {version}")
