//go:build windows

package main

import _ "embed"

// Generated by scripts/build_patch.ps1 immediately before go build.
//
//go:embed patch_payload.zip
var patchPayload []byte

//go:embed patch_manifest.json
var patchManifest []byte
